services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: ./.env.test
        required: true
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: mydb
      DATABASE_URL: 'postgresql://admin:password@localhost:5432/mydb?schema=public'
      NODE_ENV: test
      PORT: 8080
    image: auth-service
    container_name: auth-service
    command: npm run start:dev
    volumes:
      - ./:/app
    ports:
      - '3007:8080'
    networks:
      - good-food

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - path: ./.env.test
        required: true
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5437:5432'
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d mysql -h localhost -p 5432']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - good-food

  nginx:
    image: nginx:1-alpine
    container_name: auth-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8087:80'
    depends_on:
      - auth-service
    networks:
      - good-food

networks:
  good-food:
    external: true
