apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  NODE_ENV: 'production'
  PORT: '8080'
  APP_PORT: '8080'
  # Origines autoris√©es pour CORS (front Next.js et API). Adapter selon l'URL du front.
  CORS_ORIGINS: 'https://api.good-food.code-with-alex.com,https://app.good-food.code-with-alex.com'
  ADMIN_EMAIL: 'admin@example.com'
  ADMIN_USERNAME: 'admin'
  JWT_PUBLIC_KEY_BASE64: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAn6v2wD5P6ycIz00CH8oU
    FzvJIW/ob9f4On3aJr42yrQYUS56LfuN1P4BgApWP1d2u6AgLBA0yq8X6j1+rJgd
    R6YvGky28hP9+74F66s8EXXxrEfI+Y9awD7bY8vKmAIkam7f6Otad5nlJKPzLN9s
    eSuVfP/rl+6MJxr7LykZ2rA+ZOeNi9BHoJ2QNvV/jzBDrxpVuSmcLA0qvcDtIqy0
    40xYP7sw4yeaZ6Pc062DaurL4cfuNNcAkuDEvYilWBsYH15jJl5S/jbZqggOHAgV
    M3aCWU7T/NMLPTxRdnt3w68M2aQOc+DqELOuIh6jkxD0mNN/+xfyQyVJBCdcSgxo
    0RkbKZOJMk+Kl7lzRV+NLyJtqdx/wdNLAA65Gx7USjlNHb7HeMsLWrY8ZVBiZRLX
    +ReuO8+aZI3CvmUzAYpnMbg+GJ1SZt8Zzx3KSm/0ay3Bt5tYwvr5okToJvR6Uh9r
    rwDuVerri4sNxrJ6Bk59kZZrk3kW5AuNbEIvZUyDhPAo2p/HqU44TmcftQSvI0k2
    sKGUELix5ClhB89q7Ypch4H4SUu6CiNs3V4nPPJ2dnRXnrYkoQocFZsTdBLjUbSg
    G/+1qlk1Bl64I0ZqZkgBImSrJF48e2Y+qgpQy9cHcujA1uhK9V0CfwT45eQBK9kV
    4a1VWyZO3NWV08oELwZaly8CAwEAAQ==
    -----END PUBLIC KEY-----
  JWT_PRIVATE_KEY_BASE64: |
    -----BEGIN PRIVATE KEY-----
    MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAgICAQCfq/bAPk/rJwjP
    TQI/yHQXO8khb+hv1/g6fdomvjbKtBhRLnot+43U/gGACpYP1d2u6AgLBA0yq8X
    6j1+rJgdR6YvGky28hP9+74F66s8EXXxrEfI+Y9awD7bY8vKmAIkam7f6Otad5nl
    JKPzLN9seSuVfP/rl+6MJxr7LykZ2rA+ZOeNi9BHoJ2QNvV/jzBDrxpVuSmcLA0q
    vcDtIqy040xYP7sw4yeaZ6Pc062DaurL4cfuNNcAkuDEvYilWBsYH15jJl5S/jbZ
    qggOHAgVM3aCWU7T/NMLPTxRdnt3w68M2aQOc+DqELOuIh6jkxD0mNN/+xfyQyVJ
    BCdcSgxo0RkbKZOJMk+Kl7lzRV+NLyJtqdx/wdNLAA65Gx7USjlNHb7HeMsLWrY8
    ZVBiZRLX+ReuO8+aZI3CvmUzAYpnMbg+GJ1SZt8Zzx3KSm/0ay3Bt5tYwvr5okTo
    JvR6Uh9rrwDuVerri4sNxrJ6Bk59kZZrk3kW5AuNbEIvZUyDhPAo2p/HqU44Tmcft
    QSvI0k2sKGUELix5ClhB89q7Ypch4H4SUu6CiNs3V4nPPJ2dnRXnrYkoQocFZsTd
    BLjUbSgG/+1qlk1Bl64I0ZqZkgBImSrJF48e2Y+qgpQy9cHcujA1uhK9V0CfwT45e
    QBK9kV4a1VWyZO3NWV08oELwZaly8CAwEAAQKCAQC/GmxbrrisM63hnsOaFJxzk
    UR1gSWSCB6sUI1+JdPiLllKAJyPCHKp8BX5QdRDe5HG8lDciBhYrT+gHwxKbWq
    Fnb2lFj7vWfJdGkPO/J3iYAEnLB7gep7BFcof66bgX1VPp8paNDXlfYwLk3zbLgW
    3+xegQZdZMdArf7u++LxEEJN/I7km8IF00R2kZvtE5t9tD+qoSWXLP5JD0tsRNWs
    Hs22+4pEa9Ft+OHHjcZ8idO9aFucJ3pLUeLqU5r4xG+CZQVyfL++9sMHFP2zN3DG
    GXuSeCCyny7L8Q4UJIJDSwOGMKIgnfiwYr6nz0bucFmYEze08xK/QclB473uV6Ab
    wNeUCITgOhag4X4OnsbSauCJKSfWHGUlBwfRZGFdhEKQiqppOU+U9z3+3G9kR2E8
    YzGGC4HXG/a/svURmI/Bp2RmYWv2Hlua4ru84dg+l8gsMINjiQCuFr1QHMj6ZZ2/H
    AXsReOVgPcFv1mm644aft/PB0p7mvSOLkoxus3e8EeY+A1mTCupP5ToCqxndSuGS
    y6Z51e3ECmEkfqtCnvh9KNTMN37QgqFfA2M1Lpu+eTfw1VJ5MRBqHvlNY5zPLSuI
    /3K3VjhxWV42MN/q2SCVNYHrxJE3Qt4jOU1Tx1pkm4CJwdEtkYJL5Y3P3a1LgQ5S
    RpMYpXum9C6eGd3Zb19tAoIBAQdcoAc4eXRLrljRYQs3wlacPWztHqduzz/Fg70n
    2Rc3SSW2Ayz3Wn2pi7Il8di75XSEMKQiL5Er4EJLVVPVhwBAAq0iJ5OoWndFtxYS0z
    qKdLSuulLGEVeYSuN1PF5rzjgyy8EBoSaDt47ZXPvMRJLP7J699l8op0qpXxfg3L
    O1QgxKPWQlm844IfdB+xP6r0XA7jlAD8S+etfKtcgvOhfclgcrw/eWLP47/QNBjE
    SR+UxbjykJLr+lBLJ61kS06cMTH4LnhaS3/2yyzN0dfUGEjmWD8kaW3EKTLlIL6
    lZYXU+CSg3R42usPUCktIQqxOvPBv0fWeHqm/rgg+1iFG5GDAoIBAQC5Rf1rIyfz
    zaOhyecZqj+cJpP3XcuBO9nAJI+WYq6bQEt0UsI+fgJgco125qPeBCgvSncadU51
    LTu2U1CIiKQNnTY6YiaLWu4xTQcg4ILgr6WAbq55qObsU4Z77gKm1nqenf1aQm6S
    YBX8JGVZkcwDL01VZ9A6Vlisn/i0lJ6b02cnzHMkfjSoU9T8tkyRiIlnC/1IAtZmo
    phtBHFe0jly9Xeq3U52N/VhBA44TAyPummdI/T0t9OH7RlS+MiLFFMvujuJLC39K
    IL5QbDpcSNG5nfvx3Ybu0JTVrU9a2LGZsGo9Vf3zvV12lhlhIeXiU6Z5FvEmnZWU
    d2CPcnc57k/lAoIBACoFCJsG9tFbOWtXck2CZACJ6m8XAYinFwQBTzLqhJLl+G
    J1BGNdXq11lGwKK4xwJOcPH54UpcAgRbAAlIDUQzwZN4N+Vq1XJ0xhuxp2MMMVM30
    2Up9Gb7DGtNviYGNsbZy77FtJItqbVYckh63wNe67T+cY1Kn3u2stOO9WM2WyTgo
    GxRSmuCfJdCfMGoFD70oE7FMhGdT/A5wxDLnbPTlzYMsuEVXK6MN8yKLJ0owBRDZ
    rVUkZDfHtz6SBK/4PcEspT/3QjIRIeDEB/EP5CSdAlSpFiyxcrSZg+LlFODrlLMZ
    65voFp/NYrx77RhAPTFHAXqxIcgPQS71sYaWoZIRAoIBABpWHKPyJ2e8v5nr/IkN
    lmU4BqiPKLKCM33gtJiIBpIDHba3XO1NNEFJh1pzhq/DaCLwzuVv72swtuBAD56Y
    7dkRk/fQo/IDRwCzFmRSBciyrzAGi763h7voU6GiP7Y/nsaVZsJB1z3vcrCY699D
    ykUvEV7sFnalFhVlSD2T2WPM4awxV1Wo12aLRiPQWseoYmIZsSpwphsXIaCryrvb
    0MsKYqcUt7zLWpRDURraw2zTfgMeHGg/+y+g28L9lXu2bCo/HWPVio6bAPKlr9YW
    c9mS35GOD/Q6qi2FqVYcn4JdVXzKkILpVDPasb4Oh4MYqP1liXoXxH+KSKubdd9C
    RRECggEARYVAdt5dC5CXYWgUl7lD0jP2U01KR9R700Lo/WB1WiVFt2Fy/OUzg3Wc
    rjI29hLgRBz67eMdNbS90SpV6LotRNYs3XNv54nE0+hNlmVZMxzigVCKtSNGZV6d
    7dxZn3lGGbO5CysD9HAR1KLMOhW6JcGwWpjNlUFqSdzj/dobh1g/oGczVGqit9Gs
    tlfEKzZR5ZXqJGnASaf6qA3+rjnsdakM4pbE3jo+pfXqitXVkP37BMnZb/k9pJR/
    IQ5amli7quG061ugwyBRSEkxzlHhW09x8L4uIsbnJkcfEDHxnYi4oNHm/TzGJGnp
    /Zj9IJ2uy9GlIAEfFQN5U/WsBLBl9g==
    -----END PRIVATE KEY-----
