name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm install
      - run: docker build -t auth-service .

  lint:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm install
      - run: npm run lint

  security:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm install
      - run: npm audit

  test:
    needs: [ build ]
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB:
      DATABASE_URL: postgresql://admin:password@localhost:5432/mydb?schema=public
    steps:
      - uses: actions/checkout@v4
      - name: Set up dependecies
        run: npm install
      - name: Create network
        run: docker network create good-food
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          up-flags: '--build'
          down-flags: '--volumes'
          test-container: 'auth-service'
          compose-file: './docker-compose.test.yml'
          test-command: 'npm run test'

  build-recette:
    needs: [ test, lint, security ]
    runs-on: ubuntu-latest
    environment:
      name: recette
    steps:
      - uses: actions/checkout@v4
      - name: Set up dependecies
        run: npm install
      - name: Login docker
        run: echo ${{ secrets.SCW_SECRET }} | docker login ${{ secrets.SCW_RECETTE_CR }} -u skelletondude --password-stdin
      - name: Build image
        run: docker build -t ${{ secrets.SCW_RECETTE_CR }}/skelletondude/auth-service .
      - name: Push image
        run: docker push ${{ secrets.SCW_RECETTE_CR }}/skelletondude/auth-service